[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["dotnet restore"]

[phases.build]
cmds = ["dotnet publish -c Release -o ./publish --self-contained false /p:CopyOutputSymbolsToPublishDirectory=false"]

[start]
cmd = "dotnet ./publish/CrudApp.dll"
