[phases.setup]
nixPkgs = ["dotnet-sdk_8", "dotnet-aspnetcore_8"]

[phases.install]
cmds = ["dotnet restore"]

[phases.build]
cmds = ["dotnet publish -c Release -o /app"]

[start]
cmd = "dotnet /app/CrudApp.dll"
