[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["dotnet restore --verbosity minimal"]

[phases.build]
cmds = ["dotnet publish -c Release -o /app --no-restore"]

[start]
cmd = "dotnet /app/CrudApp.dll"
