[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["dotnet restore"]

[phases.build]
cmds = ["dotnet publish -c Release -o ./publish --self-contained true -r linux-x64 /p:CopyOutputSymbolsToPublishDirectory=false"]

[start]
cmd = "./publish/CrudApp"
